/**
 * generated by Xtext 2.10.0
 */
package bmstu_org.eclipse.xtext.web.example.mydsl;

import bmstu_org.eclipse.xtext.web.example.mydsl.MyDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {
  public static void doSetup() {
    MyDslStandaloneSetup _myDslStandaloneSetup = new MyDslStandaloneSetup();
    _myDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
