/*
 * generated by Xtext 2.10.0
 */
package bmstu_org.eclipse.xtext.web.example.mydsl.formatting2

import bmstu_org.eclipse.xtext.web.example.mydsl.myDsl.Greeting
import bmstu_org.eclipse.xtext.web.example.mydsl.myDsl.Model
import bmstu_org.eclipse.xtext.web.example.mydsl.services.MyDslGrammarAccess
import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess

	def dispatch void format(Model model, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Greeting greetings : model.getGreetings()) {
			greetings.format;
		}
	}
	
	// TODO: implement for 
}
