/*
 * generated by Xtext 2.10.0
 */
package bmstu_org.eclipse.xtext.web.example.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("bmstu_org/eclipse/xtext/web/example/mydsl/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
